apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-plotting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-plotting-app
  template:
    metadata:
      labels:
        app: llm-plotting-app
    spec:
      containers:
      - name: llm-plotting-app
        image: rowanmankoo/llm-plotting-app:latest
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: llm-plotting-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: llm-plotting-app