[tool.poetry]
name = "llm-plotting"
version = "0.1.0"
description = ""
authors = ["Rowan Mankoo <rowan.mankoo@gmail.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.1.4"
pandas = "^2.2.0"
openai = "^1.10.0"
python-dotenv = "^1.0.1"
plotly = "^5.18.0"
nbformat = "^5.9.2"
langchain-openai = "^0.0.5"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
