[global]
developmentMode = false
logLevel = "info"

[server]
headless = true
port = 5000
enableCORS = false
maxUploadSize = 980 

[browser]
gatherUsageStats = true

[theme]
base = "light"
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"